spring:
  h2:
    console:
      enabled: true
  profiles:
    default: local
    active:
      - local
    group:
      local: POR
      dev: ESP
com:
  tfcards:
    user: ymlTransformerUser
    password: ymlTransformerUser
    jdbcurl: ymlTfCardsDbSource
---
spring:
  config:
    activate:
      on-profile: local
com:
  tfcards:
    user: ymlLocalTransformerUser
    password: ymlLocalTransformerUser
    jdbcurl: ymlLocalTfCardsDbSource