spring:
  h2:
    console:
      enabled: true
  profiles:
    default: local
    active:
      - local
    group:
      local: POR
      dev: ESP
com:
  tfcards:
    user: ymlTransformerUser
    password: ymlTransformerUser
    jdbcurl: ymlTfCardsDbSource
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:tfcardsdb
com:
  tfcards:
    user: ymlLocalTransformerUser
    password: ymlLocalTransformerUser
    jdbcurl: ymlLocalTfCardsDbSource
server:
  port: 8082
logging:
  level:
    com:
      tfcards: debug